import React from "react";
import Head from "next/head";
import { motion } from "framer-motion";
import Image from "next/image";

const about = () => {
  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  };

  const item = {
    hidden: { x: -2000 },
    show: { x: 0 },
  };
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3>About</h3>
        <motion.div
          className="wall"
          variants={container}
          initial="hidden"
          animate="show"
        >
          <motion.section className="card" id="first" variants={item}>
            <p>Web Developer</p>
            <a
              href="https://github.com/pro-grammer206"
              target="_blank"
              rel="noreferrer"
            >
              <Image src="/github.svg" width={32} height={32} alt="github" />
            </a>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>Web Technologies used</p>
            <ul>
              <li>HTML</li>
              <li>CSS</li>
              <li>Javascript</li>
            </ul>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>Javascript frontends used</p>
            <ul>
              <li>Jquery</li>
              <li>React</li>
              <li>Vue</li>
            </ul>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>Nodejs framework used</p>
            <ul>
              <li>Express</li>
            </ul>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>CSS Libraries used</p>
            <ul>
              <li>Bootstrap</li>
              <li>Tailwindcss</li>
              <li>Chakra UI</li>
            </ul>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>React Animation libraries used</p>
            <ul>
              <li>React Spring</li>
              <li>Framer motion</li>
            </ul>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>Databases familiar with</p>
            <ul>
              <li>MySQL</li>
              <li>MongoDB</li>
            </ul>
          </motion.section>
          <motion.section className="card" variants={item}>
            <p>Headless CMS used</p>
            <ul>
              <li>Contentful</li>
              <li>GraphCMS</li>
            </ul>
          </motion.section>
        </motion.div>
      </main>
    </>
  );
};

export default about;
