import Head from "next/head";
import Image from "next/image";
import { GraphQLClient } from "graphql-request";
import Link from "next/link";
import moment from "moment";
import { motion } from "framer-motion";

export async function getStaticProps() {
  const graphcms = new GraphQLClient(process.env.ENDPOINT);
  const { articles } = await graphcms.request(
    `{
     articles(orderBy: publishedAt_DESC) {
    content {
      text
    }
    createdAt
    id
    slug
    title
  }
}
    `
  );
  return {
    props: {
      articles,
    },
    revalidate: 10,
  };
}

export default function Home({ articles }) {
  const container = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2,
      },
    },
  };

  const item = {
    hidden: { y: -2000 },
    show: { y: 0 },
  };
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h3 style={{ fontWeight: "bold", fontSize: "2rem" }}>My Posts</h3>
        <motion.section
          variants={container}
          initial="hidden"
          animate="show"
          className="snotes"
        >
          {articles.map((article) => (
            <Link href={`/posts/${article.slug}`} key={article.id}>
              <motion.a variants={item}>
                <section className="card">
                  <h3>{article.title}</h3>
                  <p>Posted {moment(article.createdAt).fromNow()}</p>
                </section>
              </motion.a>
            </Link>
          ))}
        </motion.section>
      </main>
    </div>
  );
}
